---

- name: Configure ElasticSearch Repository (RedHat Family)
  when: ansible_os_family == 'RedHat'
  block:
    - name: Copy ElasticSearch yum repo file
      ansible.builtin.copy:
        src: elk.repo
        dest: /etc/yum.repos.d/elk.repo
        owner: root
        group: root
        mode: '0644'

    - name: Import ElasticSearch GPG Key
      ansible.builtin.rpm_key:
        key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

- name: Configure ElasticSearch Repository (Debian Family)
  when: ansible_os_family == 'Debian'
  block:
    - name: Install apt-transport-https
      ansible.builtin.apt:
        name: apt-transport-https
        state: present

    - name: Import ElasticSearch GPG Key
      ansible.builtin.apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Add Elastic repository (Debian)
      ansible.builtin.apt_repository:
        repo: "deb https://artifacts.elastic.co/packages/9.x/apt stable main"
        state: present
        filename: elastic-9.x

- name: Creates ELK Cert Directory
  ansible.builtin.file:
    path: /etc/beat
    state: directory
    mode: '0755'
  become: true

- name: Install ELK server SSL client certificate
  ansible.builtin.get_url:
    url: "http://{{ elk_server }}:{{ elk_server_ssl_cert_port }}/beat-forwarder.crt"
    dest: /etc/beat/beat-forwarder.crt
    mode: '0644'
    force: true
  become: true
  when: effective_logging_backend != 'fluentd'
  notify: restart filebeat

- name: Install ELK server SSL client key
  ansible.builtin.get_url:
    url: "http://{{ elk_server }}:{{ elk_server_ssl_cert_port }}/beat-forwarder.key"
    dest: /etc/beat/beat-forwarder.key
    mode: '0644'
    force: true
  become: true
  when: effective_logging_backend != 'fluentd'
  notify: restart filebeat
