---

#
# install xpack suite for elasticsearch services
#

- name: Check if elasticsearch xpack is installed
  stat: path=/usr/share/elasticsearch/plugins/x-pack
  register: check_es_xpack_path

- name: Install xpack for elasticsearch
  command: /usr/share/elasticsearch/bin/elasticsearch-plugin install x-pack -b
  when: install_elasticsearch_xpack and check_es_xpack_path.stat.exists == False
  ignore_errors: true