---
#
# Playbook to install the ELK stack
#
- hosts: elasticsearch-servers
  remote_user: root
  vars_files:
    - group_vars/all.yml
  roles:
    - { role: elasticsearch }
    - { role: curator, when: install_curator_tool }
    - { role: xpack-elasticsearch, when: (install_elasticsearch_xpack) }

- hosts: logging-servers
  remote_user: root
  vars_files:
    - group_vars/all.yml
  roles:
    - { role: fluentd, when: (logging_backend == 'fluentd') }
    - { role: logstash, when: ((logging_backend is none) or (logging_backend == 'logstash')) }
    - { role: xpack-logstash, when: (install_logstash_xpack) and ((logging_backend is none) or (logging_backend == 'logstash')) }

- hosts: kibana-servers
  remote_user: root
  vars_files:
    - group_vars/all.yml
  roles:
    - { role: nginx }
    - { role: kibana }
    - { role: xpack-kibana, when: (install_kibana_xpack) }
    - { role: instructions }